import { jsPDF } from 'jspdf'
import type { FitReportResponse } from '../api/client'
import { filterGuidanceUrls } from '../api/client'

type Rgb = [number, number, number]

const COLORS = {
  primary: [0, 77, 102] as Rgb,
  accent: [92, 184, 230] as Rgb,
  text: [30, 41, 59] as Rgb,
  muted: [100, 116, 139] as Rgb,
  success: [22, 163, 74] as Rgb,
  successBg: [240, 253, 244] as Rgb,
  successBorder: [134, 239, 172] as Rgb,
  warning: [202, 138, 4] as Rgb,
  warningBg: [254, 252, 232] as Rgb,
  warningBorder: [253, 224, 71] as Rgb,
  border: [226, 232, 240] as Rgb,
  white: [255, 255, 255] as Rgb,
  planAccent: [14, 116, 144] as Rgb,
}

const PAGE_H = 297
const PAGE_W = 210
const MARGIN = 16
const CONTENT_W = PAGE_W - MARGIN * 2
const FOOTER_Y = PAGE_H - 10

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'fit-report'
}

function scoreLabel(score: number): string {
  if (score >= 80) return 'Strong match'
  if (score >= 60) return 'Good potential'
  if (score >= 40) return 'Needs preparation'
  return 'Significant gaps'
}

class FitReportPdfBuilder {
  private readonly doc: jsPDF
  private y = MARGIN

  constructor() {
    this.doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true })
  }

  private setFill(rgb: Rgb) {
    this.doc.setFillColor(rgb[0], rgb[1], rgb[2])
  }

  private setDraw(rgb: Rgb) {
    this.doc.setDrawColor(rgb[0], rgb[1], rgb[2])
  }

  private setText(rgb: Rgb) {
    this.doc.setTextColor(rgb[0], rgb[1], rgb[2])
  }

  private ensureSpace(height: number) {
    if (this.y + height > FOOTER_Y - 4) {
      this.addFooter()
      this.doc.addPage()
      this.y = MARGIN
    }
  }

  private addFooter() {
    const prevSize = this.doc.getFontSize()
    this.setText(COLORS.muted)
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(8)
    this.doc.text('Generated by SkillFit · Confidential', MARGIN, FOOTER_Y)
    this.doc.setFontSize(prevSize)
  }

  private wrappedText(text: string, x: number, maxWidth: number, lineHeight: number) {
    const lines = this.doc.splitTextToSize(text, maxWidth) as string[]
    for (const line of lines) {
      this.ensureSpace(lineHeight)
      this.doc.text(line, x, this.y)
      this.y += lineHeight
    }
  }

  private sectionTitle(title: string) {
    this.ensureSpace(12)
    this.setText(COLORS.text)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(13)
    this.doc.text(title, MARGIN, this.y)
    this.y += 2
    this.setDraw(COLORS.border)
    this.doc.setLineWidth(0.3)
    this.doc.line(MARGIN, this.y, PAGE_W - MARGIN, this.y)
    this.y += 7
  }

  private drawHeader(report: FitReportResponse) {
    const headerH = 34
    this.setFill(COLORS.primary)
    this.doc.rect(0, 0, PAGE_W, headerH, 'F')

    this.setText(COLORS.white)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(18)
    this.doc.text('SkillFit', MARGIN, 14)

    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(9)
    this.doc.text('Role Readiness Report', MARGIN, 21)

    const dateStr = new Date().toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
    this.doc.text(dateStr, PAGE_W - MARGIN, 14, { align: 'right' })

    this.y = headerH + 10

    const title = report.job_title || 'Fit Report'
    this.setText(COLORS.text)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(20)
    this.doc.text(title, MARGIN, this.y)
    this.y += 8

    if (report.company_name) {
      this.setText(COLORS.muted)
      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(11)
      this.doc.text(report.company_name, MARGIN, this.y)
      this.y += 8
    } else {
      this.y += 2
    }
  }

  private drawScoreBlock(score: number, summary: string) {
    const blockH = 38
    this.ensureSpace(blockH + 4)
    const boxY = this.y

    this.setFill([248, 250, 252])
    this.setDraw(COLORS.border)
    this.doc.setLineWidth(0.4)
    this.doc.roundedRect(MARGIN, boxY, CONTENT_W, blockH, 3, 3, 'FD')

    const cx = MARGIN + 22
    const cy = boxY + blockH / 2
    this.setDraw(COLORS.accent)
    this.doc.setLineWidth(2.5)
    this.doc.circle(cx, cy, 14, 'S')
    this.setFill(COLORS.white)
    this.doc.circle(cx, cy, 11.5, 'F')

    this.setText(COLORS.primary)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(16)
    this.doc.text(`${Math.round(score)}%`, cx, cy + 1.5, { align: 'center' })

    const textX = MARGIN + 44
    const textW = CONTENT_W - 48
    this.setText(COLORS.text)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(11)
    this.doc.text('ATS Match Score', textX, boxY + 11)

    this.setText(COLORS.accent)
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(9)
    this.doc.text(scoreLabel(score), textX, boxY + 17)

    this.setText(COLORS.muted)
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(9.5)
    const summaryY = boxY + 23
    const lines = this.doc.splitTextToSize(summary, textW) as string[]
    lines.slice(0, 2).forEach((line, i) => {
      this.doc.text(line, textX, summaryY + i * 4.2)
    })

    this.y = boxY + blockH + 10
  }

  private drawAnalysisSections(
    strengths: string[],
    gaps: string[],
  ) {
    this.sectionTitle('Fit analysis')
    this.drawSubsection('What you know', strengths, 'No strengths identified yet.', 'success')
    this.drawSubsection("What you're missing", gaps, 'No major gaps identified.', 'warning')
  }

  private drawSubsection(
    title: string,
    items: string[],
    emptyLabel: string,
    tone: 'success' | 'warning',
  ) {
    this.ensureSpace(8)
    this.setText(tone === 'success' ? COLORS.success : COLORS.warning)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(10.5)
    this.doc.text(title, MARGIN, this.y)
    this.y += 6
    this.drawColumnItems(items, emptyLabel, MARGIN, CONTENT_W, tone)
    this.y += 4
  }

  private drawColumnItems(
    items: string[],
    emptyLabel: string,
    x: number,
    width: number,
    tone: 'success' | 'warning',
  ) {
    const palette =
      tone === 'success'
        ? { bg: COLORS.successBg, border: COLORS.successBorder }
        : { bg: COLORS.warningBg, border: COLORS.warningBorder }

    const list = items.length > 0 ? items : [emptyLabel]
    const italic = items.length === 0

    for (const item of list) {
      const lines = this.doc.splitTextToSize(item, width - 8) as string[]
      const itemH = lines.length * 4.2 + 4
      this.ensureSpace(itemH + 2)

      const boxY = this.y - 3
      this.setFill(palette.bg)
      this.setDraw(palette.border)
      this.doc.setLineWidth(0.25)
      this.doc.roundedRect(x, boxY, width, itemH, 1.5, 1.5, 'FD')

      this.setText(italic ? COLORS.muted : COLORS.text)
      this.doc.setFont('helvetica', italic ? 'italic' : 'normal')
      this.doc.setFontSize(9)
      lines.forEach((line, i) => {
        this.doc.text(line, x + 4, this.y + i * 4.2)
      })
      this.y += itemH + 2
    }
  }

  private drawPreparationPlan(report: FitReportResponse) {
    const plan = report.fit_report.preparation_plan
    if (plan.length === 0) return

    this.sectionTitle('Preparation plan')

    plan.forEach((item, index) => {
      const urls = filterGuidanceUrls(item.study_urls ?? [])
      const detailLines = this.doc.splitTextToSize(item.detail, CONTENT_W - 14) as string[]
      const urlLineCount = urls.reduce((count, url) => {
        return count + (this.doc.splitTextToSize(url, CONTENT_W - 18) as string[]).length
      }, 0)
      const blockH = 10 + detailLines.length * 4.2 + (urlLineCount > 0 ? 6 + urlLineCount * 3.8 : 0)

      this.ensureSpace(blockH + 4)
      const boxY = this.y - 2

      this.setFill(COLORS.white)
      this.setDraw(COLORS.border)
      this.doc.setLineWidth(0.3)
      this.doc.roundedRect(MARGIN, boxY, CONTENT_W, blockH, 2, 2, 'FD')

      this.setFill(COLORS.planAccent)
      this.doc.rect(MARGIN, boxY, 2.5, blockH, 'F')

      this.setText(COLORS.planAccent)
      this.doc.setFont('helvetica', 'bold')
      this.doc.setFontSize(10.5)
      this.doc.text(`${index + 1}. ${item.topic}`, MARGIN + 7, this.y + 4)

      this.setText(COLORS.muted)
      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(9.5)
      detailLines.forEach((line, i) => {
        this.doc.text(line, MARGIN + 7, this.y + 10 + i * 4.2)
      })

      if (urls.length > 0) {
        let urlY = this.y + 10 + detailLines.length * 4.2 + 2
        this.setText(COLORS.accent)
        this.doc.setFont('helvetica', 'bold')
        this.doc.setFontSize(8)
        this.doc.text('Resources', MARGIN + 7, urlY)
        urlY += 4
        this.doc.setFont('helvetica', 'normal')
        for (const url of urls) {
          const urlLines = this.doc.splitTextToSize(url, CONTENT_W - 18) as string[]
          for (const line of urlLines) {
            this.doc.textWithLink(line, MARGIN + 7, urlY, { url })
            urlY += 3.8
          }
        }
      }

      this.y = boxY + blockH + 5
    })
  }

  private drawKeywords(matched: string[], missing: string[]) {
    this.sectionTitle('ATS keywords')

    const drawGroup = (label: string, keywords: string[], tone: 'success' | 'warning', empty: string) => {
      this.ensureSpace(10)
      this.setText(COLORS.muted)
      this.doc.setFont('helvetica', 'bold')
      this.doc.setFontSize(8)
      this.doc.text(label.toUpperCase(), MARGIN, this.y)
      this.y += 5

      if (keywords.length === 0) {
        this.setText(COLORS.muted)
        this.doc.setFont('helvetica', 'italic')
        this.doc.setFontSize(9)
        this.doc.text(empty, MARGIN, this.y)
        this.y += 7
        return
      }

      const text = keywords.join('  ·  ')
      const palette =
        tone === 'success'
          ? { bg: COLORS.successBg, border: COLORS.successBorder, color: COLORS.success }
          : { bg: COLORS.warningBg, border: COLORS.warningBorder, color: COLORS.warning }

      const lines = this.doc.splitTextToSize(text, CONTENT_W - 8) as string[]
      const boxH = lines.length * 4.5 + 5
      this.ensureSpace(boxH)

      this.setFill(palette.bg)
      this.setDraw(palette.border)
      this.doc.roundedRect(MARGIN, this.y - 3, CONTENT_W, boxH, 2, 2, 'FD')

      this.setText(palette.color)
      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(9)
      lines.forEach((line, i) => {
        this.doc.text(line, MARGIN + 4, this.y + 1 + i * 4.5)
      })
      this.y += boxH + 4
    }

    drawGroup('Matched', matched, 'success', 'None matched yet.')
    drawGroup('Missing', missing, 'warning', 'No missing keywords.')
  }

  private drawFullSummary(summary: string) {
    this.sectionTitle('Executive summary')
    this.setText(COLORS.text)
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(10)
    this.wrappedText(summary, MARGIN, CONTENT_W, 5)
    this.y += 4
  }

  build(report: FitReportResponse): jsPDF {
    const fit = report.fit_report
    this.drawHeader(report)
    this.drawScoreBlock(fit.overall_fit_score, fit.role_readiness_summary)
    this.drawFullSummary(fit.role_readiness_summary)
    this.drawAnalysisSections(fit.strengths, fit.gaps)
    this.drawPreparationPlan(report)
    this.drawKeywords(fit.ats_keywords_matched, fit.ats_keywords_missing)
    this.addFooter()
    return this.doc
  }
}

export function downloadFitReportPdf(report: FitReportResponse): void {
  const builder = new FitReportPdfBuilder()
  const doc = builder.build(report)
  const titlePart = slugify(report.job_title || 'fit-report')
  const companyPart = report.company_name ? `-${slugify(report.company_name)}` : ''
  doc.save(`skillfit-${titlePart}${companyPart}-fit-report.pdf`)
}
